### ISSUE TITLE
ci: put data files in a place that we can pull

### ISSUE THREAD

**Issue by michaelsevilla** [uccross/skyhookdb-ceph#10]
Right now we package this into a Docker container, built from our skyhook1 node as shown [here](https://github.com/uccross/skyhookdb-ceph/blob/ci-stages/ci/docker/build.sh#L4). Once we do this, we can automate the building and pushing of a Docker container in a different Travis stage.

**Comment by jlefevre** [comment]
I have been checking into using our science DMZ, what do we need in terms of:
- disk space needed
- R/W permissions
- public or ssh-key access

For now I have some test data files [here](https://users.soe.ucsc.edu/~jlefevre/skyhookdb/testdata/) and could put the docker file but would be hard to automate using this location.

**Comment by michaelsevilla** [comment]
#14 stores the data files in containers.
