### ISSUE TITLE
Fix aggregation query in wiki

### ISSUE THREAD

**Issue by aditigupta17** [uccross/skyhookdb-ceph#105]
In [Run test queries](https://github.com/uccross/skyhookdm-ceph/wiki/Run-test-queries) page in the wiki, under the basic aggregation queries section, equivalent query for 
`SELECT SUM(tax) FROM lineitem WHERE orderkey>=5;` is given as

`bin/run-query --num-objs 2 --pool tpchdata --oid-prefix "public" --table-name "lineitem" --select "orderkey,geq,5;tax,sum,0;"`

However, this gives a wrong output when used with `OBJ_TYPE=SFT_FLATBUF_FLEX_ROW`:
![image](https://user-images.githubusercontent.com/23054160/83421073-28a7b680-a445-11ea-91e6-23c2ce219a2d.png)

A `--project` tag fixes this however:
![image](https://user-images.githubusercontent.com/23054160/83421187-4d039300-a445-11ea-897f-b03e15b938e5.png)

Hence, the query should be formed as follows:
` bin/run-query --num-objs 2 --pool tpchdata --oid-prefix "public" --table-name "lineitem" --select "orderkey,geq,5;tax,sum,0;" --project "tax"`

Please make necessary changes in the wiki.

**Comment by jlefevre** [comment]
done, thank you.

**Comment by jlefevre** [comment]
done, thanks!
