### ISSUE TITLE
upgrade ceph

### ISSUE THREAD

**Issue by noahdesu** [uccross/skyhookdb-ceph#8]
check me on this, but I think that kraken is end of life. i think the only thing in here skyhook related is the cls plugin, and that should port forward without changes (maybe some headers). the main issue in the short-term that might bite you is if kraken packages aren't available pre-built, but if you are building ceph debs from scratch, i guess it doesn't matter.

**Comment by jlefevre** [comment]
Builds and tests ok with luminous.  I will finish this tomorrow with some help from Noah.

**Comment by jlefevre** [comment]
Fixed with [commit](https://github.com/uccross/skyhookdb-ceph/commit/c04bbab794aae7380a8282852d0a99067157ca02).

Created new dev branch "skyhook-luminous".
